#ifndef GLOBALDEFS_H_INCLUDED
#define GLOBALDEFS_H_INCLUDED

// progress bars
enum progressbartype {
  PROGRESSBAR_CONSOLE,
  PROGRESSBAR_HORIZONTAL,
  PROGRESSBAR_DISC,
  PROGRESSBAR_TILTEDDISC,
  PROGRESSBAR_TILTINGDISC
};

// input
enum inputmodetype {
  INPUTMODE_MOVING_HEAD_AND_BODY,
  INPUTMODE_MOVING_HEAD,
  INPUTMODE_MOVING_HEAD_AND_ARMS,
  INPUTMODE_MOVING_ARMS
};


#endif // GLOBALDEFS_H_INCLUDED
