#ifndef GLOBALDEFS_H_INCLUDED
#define GLOBALDEFS_H_INCLUDED

// progress bars
enum progressbartype {
  PROGRESSBAR_CONSOLE,
  PROGRESSBAR_HORIZONTAL,
  PROGRESSBAR_DISC,
  PROGRESSBAR_TILTEDDISC,
  PROGRESSBAR_TILTINGDISC
};

enum inputmodetype {
  INPUTMODE_WALKING,
  INPUTMODE_SWINGING,
  INPUTMODE_SWINGING_HEADFIXED
};

#define PROTOCOLVERSION "0100"

#endif // GLOBALDEFS_H_INCLUDED
